### ISSUE TITLE
Infografía FASES DEL CICLO DE VIDA DEL DESARROLLO DE UN SISTEMA

### ISSUE THREAD

**Issue by SandyMarissaGs** [SistemasTecTlaxiaco/actividad-1-infografia-SandyMarissaGs#2]
![1](https://github.com/user-attachments/assets/bf3fd723-53e6-4027-bf4e-d9df7011f66e)
![2](https://github.com/user-attachments/assets/cab5686f-4922-4477-b7b4-3ad89f44fb10)

**Comment by PedroGarcia15** [comment]
El trabajo esta bien hecho, cumple con los puntos que pide la rubrica.
La calificación final es 20/20

**Comment by Roldanuriel** [comment]
20 / 20  describe claramente cada uno de los puntos dentro de la infografía

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
